### ISSUE TITLE
Compiler message: /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:4:7: Error: The type 'Diagnosticable' can't be used as supertype. class DatePickerTheme extends Diagnosticable {

### ISSUE THREAD

**Issue by Kassan424kh** [Realank/flutter_datetime_picker#124]
At last update of dart Language on my windows PC and Flutter package I can't start my Project anymore, I get every time this error message:
```LOG
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:4:7: Error: The type 'Diagnosticable' can't be used as supertype.
class DatePickerTheme extends Diagnosticable {
```
```LOG
C:\Users\me\Desktop\bh_app>flutter doctor -v
[√] Flutter (Channel master, v1.15.22-pre.24, on Microsoft Windows [Version 10.0.18363.657], locale de-DE)
    • Flutter version 1.15.22-pre.24 at C:\src\flutter
    • Framework revision aba0e2dc8f (2 days ago), 2020-03-13 23:21:03 -0400
    • Engine revision e48761e5bb
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 c3a0bb086a)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29905.134

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.657]
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

```YAML
name: bh_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  google_fonts: ^0.3.2
  outline_material_icons: ^0.1.1
  flutter_datetime_picker: ^1.3.5 <----- here is the package
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.2.0
  path: ^1.6.4
  loading: ^1.0.2
  dio: ^3.0.8
  jose: ^0.1.2
  pdf: ^1.5.0
  printing: ^3.1.0
  js: ^0.6.1+1
  crypted_preferences: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
