### ISSUE TITLE
No named parameter with the name 'shadowThemeOnly'

### ISSUE THREAD

**Issue by Kassan424kh** [Realank/flutter_datetime_picker#215]
``` LOG
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart(215,48): error GBF4691A2: No named parameter with the name 'shadowThemeOnly'. [C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\CMakeFiles\277d9f2a3f146cf30fc269906d554467\flutter_windows.dll.rule;C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\CMakeFiles\4efcb42468d70c4d6a918b2c50c86d78\flutter_assemble.rule' exited with code 1. [C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\flutter\flutter_assemble.vcxproj]
```

```yml
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  path_provider: ^1.6.27
  google_fonts: ^1.1.1
  outline_material_icons: ^0.1.1
  flutter_datetime_picker: ^1.4.0
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.3.2+2
  path: ^1.6.4
  loading: ^1.0.2
  dio: ^3.0.8
  jose: ^0.2.1+1
  pdf: ^1.13.0
  printing: ^3.7.2
  js: ^0.6.1+1
  crypted_preferences: ^0.0.2
  unicode: ^0.2.2
  shared_preferences: ^0.5.12+4
  build_runner: ^1.10.13
  build_web_compilers: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

```dart
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';

class UIDatePicker extends DatePicker {
  static d(BuildContext context, selectedTheme, DateTime date, onConfirm, {DateTime maxDate}) {
    return DatePicker.showDatePicker(
      context,
      theme: DatePickerTheme(
        backgroundColor: selectedTheme[ElementStylingParameters.primaryColor],
        itemStyle: TextStyle(
          color: selectedTheme[ElementStylingParameters.headerTextColor],
        ),
        cancelStyle: TextStyle(
          color: selectedTheme[ElementStylingParameters.logoutButtonColor],
        ),
        doneStyle: TextStyle(
          color: selectedTheme[ElementStylingParameters.editButtonColor],
        ),
      ),
      showTitleActions: true,
      maxTime: maxDate == null ? DateTime.now(): maxDate,
      onConfirm: onConfirm,
      currentTime: date,
      locale: LocaleType.de,
    );
  }
}
```

**Comment by ajbarry** [comment]
@Realank this appears to be fixed in the master branch. Could you publish a new 1.4.1 version?

@Kassan424kh you can work around this issue as I have with a git package reference:
```yaml
dependencies:
  flutter_datetime_picker:
    git: git@github.com:Realank/flutter_datetime_picker.git
```
