### ISSUE TITLE
Issue with Null Safety Latest version

### ISSUE THREAD

**Issue by lcsvcn** [Realank/flutter_datetime_picker#235]
This is shown at output when running latest github version.
```
../../.pub-cache/git/flutter_datetime_picker-7701e6af230bccd53fa86f6eb6cabd6b661c2665/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
```

**Comment by onlycyndi** [comment]
I have same problem - -#

**Comment by AlexHartford** [comment]
It's just a warning, so you can safely ignore it. I have a PR https://github.com/Realank/flutter_datetime_picker/pull/236 out to fix it. 
If it bothers you, you can pull from my branch like so:
```yaml
flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
```
