### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by swch01** [Realank/flutter_datetime_picker#242]
PR #236 fixed the problem reported in issues #241, #239, and #328. You merged the fix on April 22nd, but you didn't update the version. Users will be pulling the broken code until you bump the version.

**Comment by AlexHartford** [comment]
Until the update is pushed, the following is a workaround.
```yaml
flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
```
