### ISSUE TITLE
null-safe error

### ISSUE THREAD

**Issue by piotritagsolutions** [Realank/flutter_datetime_picker#244]
It is not null-safe

../../Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,

**Comment by freeala** [comment]
mine too.

**Comment by AlexHartford** [comment]
Until the update is pushed, the following is a workaround.
```yaml
flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
```
