### ISSUE TITLE
Theme color error

### ISSUE THREAD

**Issue by mertcan-tas** [Realank/flutter_datetime_picker#274]
I got the following error regarding colors in the library.

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                  
![Capture](https://user-images.githubusercontent.com/62576202/136601957-206d8ced-8c7a-4bc8-9d11-87f5eb17057b.PNG)

**Comment by sebastian-schmid** [comment]
I get the same error using Linux as development system.

```
Flutter is already up to date on channel stable
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (11 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```

**Comment by sebastian-schmid** [comment]
Looks like a duplicate of #269 #253 #239

Solution for now seems to be:

```
flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master 
```
