### ISSUE TITLE
Warning on using this component

### ISSUE THREAD

**Issue by alarmatwork** [Realank/flutter_datetime_picker#289]
```
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
```

**Comment by emilmammadov** [comment]
I checked the repo and it seems they fixed that but did not deploy a new version.
You can import the package by git url and last commit hash like below. It will be fixed.
```
flutter_datetime_picker:
    git:
      url: git://github.com/Realank/flutter_datetime_picker.git
      ref: eb66486c47d50bf550950c196486121ffcea8885
```
