### ISSUE TITLE
Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.

### ISSUE THREAD

**Issue by devsigofficial** [Realank/flutter_datetime_picker#298]
../../../.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                               ^

**Comment by justintoth** [comment]
Any update on this? I'm encountering the same error after integrating this plugin.

**Comment by aliazxs** [comment]
me too

**Comment by justintoth** [comment]
This was "solved" for me by changing my pubspec entry to the following:

```
flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
```
