### ISSUE TITLE
DateTime Scrolling/picking problem only on Flutter Web

### ISSUE THREAD

**Issue by matteoberla** [Realank/flutter_datetime_picker#331]
Hi, i've implemented this package on my project, on iOS and Android it's working fine, but when running it on web it's not working 100%.
When scrolling down with the mouse wheel the picker moves by 3 steps at a time so some dates (or times) are impossible to pick.
Any solution?

**Comment by fa0311** [comment]
I have created a Fork that fixes this issue.

```yaml
dependencies:
  flutter_datetime_picker_sharp:
    git:
      url: https://github.com/fa0311/flutter_datetime_picker_sharp
```
